import { NextResponse } from "next/server";
import { prisma } from "@/src/lib/db";
import * as XLSX from "xlsx";
import PDFDocument from "pdfkit";
import {getActorFromRequest,isOwner,unauthorized,forbidden} from "@/src/lib/auth";
export const runtime = "nodejs";
const binary = (b: Buffer) => b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer;
const number = (v: unknown) => Number(v ?? 0);
function clientHeaders() { return ["Операция","Дата","Сумма, ₽","Тариф, %","Отправлено, USDT","Курс отправки, ₽/USDT"]; }
function headers(full: boolean) { return full ? ["ID","Дата","Статус","Получено, ₽","Тариф, %","Доход по тарифу, ₽","Отправить, USDT","Доход на курсах, ₽","Общий доход, ₽","Расходы, ₽","Курс клиенту","Фактический курс"] : ["ID","Дата","Статус","Получено, ₽","Тариф, %","Доход по тарифу, ₽","Отправить, USDT","Расходы, ₽"]; }
function reportRow(x: any, full: boolean) { const base = [x.number, new Date(x.date).toLocaleDateString("ru-RU"), x.status, number(x.receivedAmount), number(x.tariffPercent), number(x.expectedCommission), number(x.sentAmount)]; return full ? [...base, number(x.exchangeProfit), number(x.totalProfit ?? x.actualResult), number(x.expenses), number(x.clientRate), number(x.actualExchangeRate)] : [...base, number(x.expenses)]; }
function cyrillicFont() { const candidates = [process.env.PDF_FONT_PATH, "C:\\Windows\\Fonts\\arial.ttf", "C:\\Windows\\Fonts\\segoeui.ttf", "C:\\Windows\\Fonts\\tahoma.ttf"].filter(Boolean) as string[]; for (const p of candidates) { try { if (require("fs").existsSync(p)) return p; } catch {} } return null; }
async function createPdf(title: string, data: any[][], full: boolean, client = false) { const doc = new PDFDocument({ size: "A4", margin: 35 }); const chunks: Buffer[] = []; doc.on("data", (chunk: Buffer) => chunks.push(chunk)); const done = new Promise<Buffer>((resolve, reject) => { doc.on("end", () => resolve(Buffer.concat(chunks))); doc.on("error", reject); }); const font = cyrillicFont(); if (font) doc.font(font); doc.fontSize(16).text(title); doc.moveDown().fontSize(8).text(`Операций: ${data.length}`); doc.moveDown(); const statusName=(v:string)=>({DRAFT:"Черновик",PROCESSING:"В работе",COMPLETED:"Завершена",CANCELLED:"Отменена"}[v]??v); const money=(v:unknown)=>number(v).toFixed(2); data.forEach((r) => { const text=client ? `Операция №${r[0]} | ${r[1]} | сумма ${money(r[2])} ₽ | тариф ${r[3]}% | отправлено ${Number(r[4]).toFixed(4)} USDT | курс ${money(r[5])} ₽/USDT` : full ? `Операция №${r[0]} | ${r[1]} | ${statusName(r[2])}`+`\nПолучено: ${money(r[3])} ₽ | Тариф: ${r[4]}% | Доход по тарифу: ${money(r[5])} ₽`+`\nКлиенту: ${Number(r[6]).toFixed(4)} USDT | Курс клиенту: ${money(r[9])} ₽/USDT | Фактический: ${money(r[10])} ₽/USDT | Доход на курсах: ${money(r[7])} ₽ | Общий доход: ${money(r[8])} ₽` : `Операция №${r[0]} | ${r[1]} | ${statusName(r[2])}`+`\nПолучено: ${money(r[3])} ₽ | Тариф: ${r[4]}% | Доход по тарифу: ${money(r[5])} ₽ | Клиенту: ${Number(r[6]).toFixed(4)} USDT`; doc.text(text); doc.moveDown(0.5); }); doc.end(); return done; }
export async function GET(req: Request) { const actor=await getActorFromRequest(req);if(!actor)return unauthorized();if(!isOwner(actor))return forbidden(); const q = new URL(req.url).searchParams; const client = q.get("mode") === "client"; const full = q.get("mode") === "full"; const format = q.get("format") ?? "csv"; const where: any = {}; const status = q.get("status"), from = q.get("from"), to = q.get("to"); if (status) where.status = status; if (from || to) where.date = { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59`) } : {}) }; const rows = await prisma.operation.findMany({ where, orderBy: { number: "asc" } }); const data = client ? rows.map((x) => [x.number,new Date(x.date).toLocaleDateString("ru-RU"),number(x.receivedAmount),number(x.tariffPercent),number(x.sentAmount),number(x.clientRate)]) : rows.map((x) => reportRow(x, full)); const head = client ? clientHeaders() : headers(full); if (format === "xlsx") { const sheet = XLSX.utils.aoa_to_sheet([head, ...data]); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "Отчёт"); const out = XLSX.write(book, { type: "buffer", bookType: "xlsx" }); return new NextResponse(binary(out), { headers: { "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": "attachment; filename=report.xlsx" } }); } if (format === "pdf") { try { const out = await createPdf(client ? "Отчёт" : (full ? "Отчёт с дополнительным доходом" : "Отчёт без дополнительного дохода"), data, full, client); return new NextResponse(binary(out), { headers: { "content-type": "application/pdf", "content-disposition": "attachment; filename=report.pdf" } }); } catch (error) { return NextResponse.json({ error: String(error) }, { status: 500 }); } } const quote = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const csv = [head, ...data].map((r) => r.map(quote).join(",")).join("\n"); return new NextResponse("\uFEFF" + csv, { headers: { "content-type": "text/csv; charset=utf-8", "content-disposition": "attachment; filename=report.csv" } }); }





